import type { Metadata } from "next";
import { Providers } from "./providers";
import { Flex } from "@chakra-ui/react";
import { GAP } from "@/constants";
import { MobileNav, Nav } from "@/components";

export const metadata: Metadata = {
  title: "Jim Burch | Software Engineer & Creative Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MobileNav />
          <Flex
            as="main"
            w="full"
            h={{ base: "full", lg: "100vh" }}
            gap={GAP}
            p={{ base: 0, lg: GAP }}
          >
            <Nav />
            {children}
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
