import type { Metadata } from "next";
import { Providers } from "./providers";
import { Flex } from "@chakra-ui/react";
import { GAP } from "@/constants";
import { Nav } from "@/components";

export const metadata: Metadata = {
  title: "Jim Burch | Software Engineer & Creative Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Flex as="main" w="100%" h="100vh" gap={GAP} p={GAP}>
            <Nav />
            {children}
          </Flex>
        </body>
      </Providers>
    </html>
  );
}
